version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitally-backend
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}


      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    networks:
      - vitally-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: vitally-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: https://api.vitallyoficial.com.br/api/v1
    ports:
      - "3000:3000"
    networks:
      - vitally-network

networks:
  vitally-network:
    driver: bridge