version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vitally-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: vitally_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vitally-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitally-backend
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vitally_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "8080:8080"
    networks:
      - vitally-network

  # O frontend entrará aqui depois, apontando para a porta 80/443

networks:
  vitally-network:
    driver: bridge

volumes:
  postgres_data: # Garante que os dados do banco não sumam se o contêiner reiniciar