spring.application.name=api

server.port=8080

spring.profiles.active=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
api.security.token.secret=${JWT_SECRET}